version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directories:
      - /
      - /__tests__/cdk/
    schedule:
      interval: daily
    cooldown:
      default-days: 1
      exclude:
        - 'pnpm'
    groups:
      npm:
        patterns:
          - '*'
