version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directories:
      - /
      - /__tests__/cdk/
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      exclude:
        - 'pnpm'
    ignore:
      - dependency-name: '@types/node'
        version-requirements:
          - from-version: 25.0.0
            to-version: 25.99.99
    groups:
      npm:
        patterns:
          - '*'
