name: 'Get value from AWS Systems Manager Parameter Store'
description: 'Retrieves the value of the specified parameter from the AWS Systems Manager Parameter Store.'
author: 'Kenji Saito'
inputs:
  parameter-name:
    required: true
    description: 'Parameter name'
  aws-region:
    required: true
    description: 'AWS region'
runs:
  using: 'node16'
  main: 'dist/index.js'
