packages:
  - .
  - __tests__/cdk

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

overrides:
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'

strictPeerDependencies: false
