packages:
  - .
  - __tests__/cdk
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

enablePrePostScripts: true
legacyPeerDeps: true
autoInstallPeers: true
strictPeerDependencies: false

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm
