packages:
  - .
  - __tests__/cdk

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

overrides:
  minimatch@<10.2.1: '>=10.2.1'

strictPeerDependencies: false
