packages:
  - .
  - __tests__/cdk

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  undici@<6.23.0: '>=6.23.0'

strictPeerDependencies: false
