packages:
  - .
  - __tests__/cdk

enablePrePostScripts: true
legacyPeerDeps: true
autoInstallPeers: true
strictPeerDependencies: false

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm
 - '@swc/core'
