name: 'build and test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b  # v6.2.0
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: us-west-2

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0

    - name: Create for testing parameter
      working-directory: __tests__/cdk
      run: pnx aws-cdk@latest deploy --all

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us-west-2, ap-northeast-1]

    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b  # v6.2.0
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ matrix.region }}

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0

    - name: lint
      run: pnpm lint

    - name: build
      run: pnpm build

    - name: package
      run: pnpm package

    - name: test
      run: pnpm test
